# **Artificial Neural Networks**

### **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
tf.__version__

'2.8.2'

# **Data Preprocessing**

### **import Data**

In [3]:
data=pd.read_csv('Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

### **Data Cleaning**

In [4]:
data.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])

### **Dealing with Categorical Features**

In [8]:
Le=LabelEncoder()
x[:,2]=Le.fit_transform(x[:,2])

In [9]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [11]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### **Split Data into training set and test set**

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

### **Feature Scalling**

In [13]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
x_train

array([[ 1.00150113, -0.57946723, -0.57638802, ...,  0.64920267,
         0.97481699,  1.36766974],
       [-0.99850112,  1.72572313, -0.57638802, ...,  0.64920267,
         0.97481699,  1.6612541 ],
       [-0.99850112, -0.57946723,  1.73494238, ...,  0.64920267,
        -1.02583358, -0.25280688],
       ...,
       [ 1.00150113, -0.57946723, -0.57638802, ..., -1.54035103,
        -1.02583358, -0.1427649 ],
       [ 1.00150113, -0.57946723, -0.57638802, ...,  0.64920267,
        -1.02583358, -0.05082558],
       [-0.99850112,  1.72572313, -0.57638802, ...,  0.64920267,
         0.97481699, -0.81456811]])

## **Build ANN**

### **Initializing the ANN**

In [15]:
ann=tf.keras.models.Sequential()

### **Add input layer and first hidden layer**

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### **Add second hidden layer**

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### **Add output Layer**

In [18]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## **Training the ANN**

### **Compiling the ANN**

In [19]:
ann.compile(optimizer ='adam' ,loss='binary_crossentropy' ,metrics= ['accuracy'])

### **Training the ANN on the training set**

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=400)

Epoch 1/400
250/250 [==============================] - 5s 4ms/step - loss: 0.5635 - accuracy: 0.7249
Epoch 2/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4599 - accuracy: 0.8043
Epoch 3/400
250/250 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.8100
Epoch 4/400
250/250 [==============================] - 1s 4ms/step - loss: 0.4299 - accuracy: 0.8148
Epoch 5/400
250/250 [==============================] - 1s 4ms/step - loss: 0.4242 - accuracy: 0.8202
Epoch 6/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4202 - accuracy: 0.8230
Epoch 7/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4167 - accuracy: 0.8261
Epoch 8/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4139 - accuracy: 0.8280
Epoch 9/400
250/250 [==============================] - 1s 4ms/step - loss: 0.4119 - accuracy: 0.8288
Epoch 10/400
250/250 [==============================] - 1s 4ms/step - loss: 0.4101 - accura

In [25]:
y_pred = ann.predict(x_test)
y_pred=np.where(y_pred > 0.5, 1, 0)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[1544   63]
 [ 217  176]]
0.86


In [24]:
y_pred=np.where(y_pred > 0.5, 1, 0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])